# Site settings
title: Java and Angular in the Cloud
description: Java and Angular
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://javaee.ch"
repository_url: "https://github.com/marco76/marco76.github.io/blob/master/"

news: "[Garbage Collectors for busy Java developers (10 min, no maths ;) )](http://javaee.ch/garbage-collectors-intro)"
# User settings
username: marco
user_description: Marco freelance architect and developer
email: moltenma@gmail.com
twitter_username: marcomolteni
github_username:  marco76
gplus_username:  lorem_ipsum
disqus_username: disqus_A4h38613IE

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
